### PR TITLE
creation model nvt

### PR DESCRIPTION
**Pull request by Joe-woods**
creation du model NVT reference a confirmer

### CODE REVIEW

**Review by MBOZAR — CHANGES_REQUESTED** [review]
@Rox1610 will submit changes 
please review them

**Review by Joe-woods — COMMENTED** [review]
ok

**Comment by Joe-woods** [comment]
ajout des controller et des routes

**Review by MBOZAR — CHANGES_REQUESTED** [review]
Few changes to be made in controller

**Review by Rox1610 — CHANGES_REQUESTED** [review]
create the actions in the controller

**Review by TheRealCL — CHANGES_REQUESTED** [review]
requesting changes !

**Comment by Joe-woods** [comment]
controller v2 + route

**Review by Rox1610 — APPROVED** [review]
good to go

**Review by TheRealCL — APPROVED** [review]
All good !

**Review by MBOZAR — APPROVED** [review]
Methods / approved and route , good job

**Pull request merged**
